#!/usr/bin/env bash
set -Eeuo pipefail

# x-ui-pro - simplified core installer
# Fork: aghajani82/x-ui-pro
# Scope: Nginx + Let's Encrypt + 3x-UI 3.7.0 + Xray + reverse-proxy subscription.
# Deliberately excludes WARP, v2rayA, sing-box/ArgosBX, Tor, random-site installers,
# SSH-port changes and automatic UFW changes from the main installation path.

XUI_VERSION="v3.7.0"
DOMAIN=""
PANEL_PORT=""
PANEL_PATH=""

log(){ printf '\033[1;36m[INFO]\033[0m %s\n' "$*"; }
ok(){ printf '\033[1;32m[ OK ]\033[0m %s\n' "$*"; }
warn(){ printf '\033[1;33m[WARN]\033[0m %s\n' "$*"; }
die(){ printf '\033[1;31m[FAIL]\033[0m %s\n' "$*" >&2; exit 1; }

usage(){
  cat <<'EOF'
Usage:
  bash x-ui-pro.sh -subdomain test.example.com

Required:
  -subdomain DOMAIN        Public domain pointing to this server

Accepted compatibility options:
  -panel 1                 Install 3x-UI (always pinned to v3.7.0)
  -xuiver VERSION          Ignored; version is intentionally pinned to v3.7.0
  -cdn on|off              Retained for compatibility; no Cloudflare-only gate is added
  -secure yes|no           Retained for compatibility; no extra Basic Auth is added
  -country XX              Retained for compatibility; no country filter is added
EOF
}

is_port(){ [[ "$1" =~ ^[0-9]+$ ]] && ((1 <= 10#$1 && 10#$1 <= 65535)); }
is_domain(){ [[ "$1" =~ ^([A-Za-z0-9]([A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)+[A-Za-z]{2,63}$ ]]; }

while (($#)); do
  case "$1" in
    -subdomain|--domain|-d)
      DOMAIN="${2:-}"; shift 2;;
    -panel|-xuiver|-cdn|-secure|-country)
      [[ $# -ge 2 ]] || die "Missing value for $1"; shift 2;;
    -h|--help)
      usage; exit 0;;
    *)
      die "Unknown option: $1";;
  esac
done

[[ $EUID -eq 0 ]] || die "Run as root."
[[ -f /etc/os-release ]] || die "Cannot detect OS."
. /etc/os-release
[[ "$ID" == "ubuntu" ]] || die "This installer targets Ubuntu."
[[ "${VERSION_ID:-}" == "24.04" ]] || warn "Tested target: Ubuntu 24.04; detected ${PRETTY_NAME:-unknown}."

[[ -n "$DOMAIN" ]] || read -r -p "Domain: " DOMAIN
DOMAIN="${DOMAIN//[[:space:]]/}"
is_domain "$DOMAIN" || die "Invalid domain: $DOMAIN"

if [[ "$DOMAIN" == www.* ]]; then
  warn "Using a www host as the service domain is not recommended."
fi

PUBLIC_IP="$(curl -4fsSL --max-time 10 https://api.ipify.org || true)"
DNS_IP="$(getent ahostsv4 "$DOMAIN" | awk 'NR==1{print $1}')"
[[ -n "$PUBLIC_IP" ]] || die "Could not determine the server IPv4 address."
[[ -n "$DNS_IP" ]] || die "Could not resolve $DOMAIN."
[[ "$DNS_IP" == "$PUBLIC_IP" ]] || die "DNS mismatch: $DOMAIN -> $DNS_IP, server -> $PUBLIC_IP"
ok "DNS: $DOMAIN -> $PUBLIC_IP"

log "Installing base packages..."
export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y nginx certbot python3-certbot-nginx sqlite3 curl ca-certificates openssl jq

mkdir -p /var/www/html /etc/nginx/sites-available /etc/nginx/sites-enabled
rm -f /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default

# Temporary HTTP-only server used solely for ACME webroot validation.
cat > /etc/nginx/sites-available/aghajani <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;
    root /var/www/html;
    location /.well-known/acme-challenge/ { try_files \$uri =404; }
    location / { return 404; }
}
EOF
ln -sfn /etc/nginx/sites-available/aghajani /etc/nginx/sites-enabled/aghajani
nginx -t
systemctl enable --now nginx
systemctl reload nginx

log "Requesting Let's Encrypt certificate..."
mkdir -p /var/www/html/.well-known/acme-challenge
certbot certonly --webroot -w /var/www/html \
  --non-interactive --agree-tos --register-unsafely-without-email \
  --cert-name "$DOMAIN" -d "$DOMAIN"

[[ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]] || die "Certificate was not created."
ok "SSL certificate ready."

log "Installing 3x-UI $XUI_VERSION..."
bash <(curl -Ls "https://raw.githubusercontent.com/MHSanaei/3x-ui/$XUI_VERSION/install.sh") "$XUI_VERSION"

command -v x-ui >/dev/null 2>&1 || die "3x-UI installation did not provide the x-ui command."
[[ -f /etc/x-ui/x-ui.db ]] || die "3x-UI database was not created."

# Read the panel defaults generated by the official installer.
x-ui stop >/dev/null 2>&1 || true
PANEL_PORT="$(sqlite3 /etc/x-ui/x-ui.db "SELECT value FROM settings WHERE key='webPort' LIMIT 1;")"
PANEL_PATH="$(sqlite3 /etc/x-ui/x-ui.db "SELECT value FROM settings WHERE key='webBasePath' LIMIT 1;")"

is_port "$PANEL_PORT" || die "Could not determine 3x-UI panel port."
[[ -n "$PANEL_PATH" ]] || PANEL_PATH="/"
[[ "$PANEL_PATH" == /* ]] || PANEL_PATH="/$PANEL_PATH"
[[ "$PANEL_PATH" == */ ]] || PANEL_PATH="$PANEL_PATH/"

# Keep panel/subscription origins local. Public access is through Nginx :443 only.
log "Configuring subscription service..."
sqlite3 /etc/x-ui/x-ui.db <<EOF
BEGIN;
DELETE FROM settings
WHERE key IN ('subEnable','subListen','subPort','subPath','subDomain','subURI');
INSERT INTO settings (key,value) VALUES
  ('subEnable','true'),
  ('subListen','127.0.0.1'),
  ('subPort','2096'),
  ('subPath','/sub/'),
  ('subDomain','$DOMAIN'),
  ('subURI','https://$DOMAIN/2096/sub/');
COMMIT;
EOF

# Nginx is the only public HTTP(S) entrypoint for the panel, subscription and Xray paths.
cat > /etc/nginx/sites-available/aghajani <<EOF
server {
    server_tokens off;
    listen 80;
    listen [::]:80;
    server_name $DOMAIN;
    root /var/www/html;
    location /.well-known/acme-challenge/ { try_files \$uri =404; }
    location / { return 301 https://\$host\$request_uri; }
}

server {
    server_tokens off;
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN;

    ssl_certificate /etc/letsencrypt/live/$DOMAIN/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/$DOMAIN/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    # 3x-UI panel / WebSocket.
    location $PANEL_PATH {
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_read_timeout 1d;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:$PANEL_PORT;
    }

    # Subscription API. The 3x-UI subscription server is HTTP on localhost;
    # TLS is terminated by Nginx on :443.
    location ~ ^/2096/sub/(?<subpath>.*)$ {
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_read_timeout 1d;
        proxy_redirect off;
        proxy_pass http://127.0.0.1:2096/sub/\$subpath\$is_args\$args;
    }

    # Xray protocol paths. Clients connect to :443; Xray listens locally on
    # the inbound port embedded in the URL path (for example /59535/ws).
    # No X-Forwarded-For header is injected here to avoid the Xray warning
    # about an untrusted forwarded address.
    location ~ ^/(?<fwdport>[0-9]+)/(?<fwdpath>.*)$ {
        client_max_body_size 0;
        client_body_timeout 1d;
        proxy_read_timeout 1d;
        proxy_send_timeout 1d;
        proxy_http_version 1.1;
        proxy_buffering off;
        proxy_request_buffering off;
        proxy_socket_keepalive on;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_redirect off;
        proxy_pass http://127.0.0.1:\$fwdport\$is_args\$args;
    }

    location / { return 404; }
}
EOF

nginx -t
systemctl reload nginx

# Persist panel/subscription settings and start 3x-UI.
x-ui start >/dev/null 2>&1 || systemctl restart x-ui
systemctl enable x-ui >/dev/null 2>&1 || true
sleep 2

# Renewal: the certbot nginx plugin reloads Nginx after renewal.
if ! systemctl list-timers --all | grep -q 'certbot.timer'; then
  systemctl enable --now certbot.timer >/dev/null 2>&1 || true
fi

# Lightweight diagnostics. Do not alter SSH or firewall configuration here.
x-ui -v || true
nginx -t
systemctl is-active --quiet nginx || die "Nginx is not active."
systemctl is-active --quiet x-ui || die "x-ui is not active."

printf '\n'
ok "Installation completed."
printf 'Domain:        %s\n' "$DOMAIN"
printf 'Panel:         https://%s%s\n' "$DOMAIN" "$PANEL_PATH"
printf 'Subscription:  https://%s/2096/sub/\n' "$DOMAIN"
printf 'Panel port:    %s (localhost via Nginx)\n' "$PANEL_PORT"
printf 'Sub port:      2096 (localhost)\n'
printf 'Xray:          managed by 3x-UI\n'
printf '\nNext step: create and test the four inbound protocols from the 3x-UI panel.\n'
